### PR TITLE
Allow inclusion in CPP projects

### PR DESCRIPTION
**Pull request by Ryzee119**
Attempted to use in Arduino, but got linker errors.
This resolved the issue.

### CODE REVIEW

**Comment by postspectacular** [comment]
Thanks, @Ryzee119! 🙏 (this was on my todo list, but personally not using C++...)

**Comment by postspectacular** [comment]
May I also ask why you've closed the PR?

**Comment by Ryzee119** [comment]
I realised i could encompass the include with extern c, without modifying your file. 😊
But will reopen for your review as this makes it an even easier addition to CPP projects.

**Comment by postspectacular** [comment]
Thanks again & that's great!! 🎉

**Comment by Ryzee119** [comment]
No problem 👍 , been using this for a few days now. Works great! Thank you

**Pull request merged**
